import { Language, Currency } from '../types';

export const EXCHANGE_RATES: Record<Currency, number> = {
  UGX: 1,
  USD: 0.00026,
  KES: 0.034,
  EUR: 0.00024,
  GBP: 0.00021
};

export const TRANSLATIONS: Record<Language, any> = {
  en: {
    title: "SACCO Risk Manager",
    dashboard: "Dashboard",
    applications: "Applications",
    wallet: "Wallet",
    members: "Members",
    advisor: "AI Risk Advisor",
    balance: "Wallet Balance",
    borrowed: "Total Borrowed",
    apply: "Apply for New Loan",
    deposit: "Deposit",
    withdraw: "Withdraw",
    payLoan: "Pay Loan",
    recentApps: "Recent Applications",
    search: "Search borrower or ID...",
    status: "Status",
    risk: "Risk",
    dates: "Dates",
    borrower: "Borrower",
    amount: "Amount",
    riskScore: "Risk Score",
    qualification: "Qualification",
    date: "Date",
    actions: "Actions",
    details: "Details",
    history: "Transaction History",
    method: "Method",
    income: "Monthly Income",
    idNumber: "National ID / Passport",
    role: "Account Type",
    member: "Member (Borrower)",
    monitor: "Monitor (Officer)",
    admin: "Administrator",
    submit: "Submit Application",
    processing: "Processing...",
    evaluating: "Evaluating Risk...",
    success: "Success",
    error: "Error"
  },
  sw: {
    title: "Meneja wa Hatari wa SACCO",
    dashboard: "Dashibodi",
    applications: "Maombi",
    wallet: "Mkoba",
    members: "Wanachama",
    advisor: "Mshauri wa AI",
    balance: "Salio la Mkoba",
    borrowed: "Jumla ya Mkopo",
    apply: "Omba Mkopo Mpya",
    deposit: "Weka Pesa",
    withdraw: "Toa Pesa",
    payLoan: "Lipa Mkopo",
    recentApps: "Maombi ya Hivi Karibuni",
    search: "Tafuta mkopaji au ID...",
    status: "Hali",
    risk: "Hatari",
    dates: "Tarehe",
    borrower: "Mkopaji",
    amount: "Kiasi",
    riskScore: "Alama ya Hatari",
    qualification: "Sifa",
    date: "Tarehe",
    actions: "Vitendo",
    details: "Maelezo",
    history: "Historia ya Muamala",
    method: "Njia",
    income: "Mapato ya Kila Mwezi",
    idNumber: "ID ya Kitaifa / Pasipoti",
    role: "Aina ya Akaunti",
    member: "Mwanachama (Mkopaji)",
    monitor: "Mfuatiliaji (Afisa)",
    admin: "Msimamizi",
    submit: "Tuma Maombi",
    processing: "Inachakata...",
    evaluating: "Inatathmini Hatari...",
    success: "Mafanikio",
    error: "Hitilafu"
  },
  lg: {
    title: "SACCO Risk Manager",
    dashboard: "Dashboard",
    applications: "Okusaba",
    wallet: "Ensawo",
    members: "Bammemba",
    advisor: "AI Risk Advisor",
    balance: "Sente eziri mu nsawo",
    borrowed: "Sente z'ewoze zonna",
    apply: "Saba looni empya",
    deposit: "Teekamu sente",
    withdraw: "Ggyamu sente",
    payLoan: "Sasula looni",
    recentApps: "Okusaba okusembyeyo",
    search: "Noonya amannya oba ID...",
    status: "Embeera",
    risk: "Obulabe",
    dates: "Ennaku",
    borrower: "Awoze",
    amount: "Omuwendo",
    riskScore: "Obulabe",
    qualification: "Okuyita",
    date: "Olunaku",
    actions: "Ebikolebwa",
    details: "Ebisingawo",
    history: "Ebyafaayo by'ensimbi",
    method: "Ngeri",
    income: "Sente z'ofuna buli mweezi",
    idNumber: "ID / Paasipooti",
    role: "Ekika ky'akaunti",
    member: "Memba (Awozi)",
    monitor: "Monitor (Afisa)",
    admin: "Administrator",
    submit: "Saba looni",
    processing: "Tukikolako...",
    evaluating: "Tupima obulabe...",
    success: "Okiyise",
    error: "Wabaddewo kiremya"
  }
};
